import sys
import json
from datetime import datetime
import os


# Simple sender: write a JSON log to an output directory (default .git/precommit_logs)
def main():
    out_dir = '.git/precommit_logs'
    args = sys.argv[1:]
    if '--out' in args:
        idx = args.index('--out')
        if idx + 1 < len(args):
            out_dir = args[idx + 1]

    os.makedirs(out_dir, exist_ok=True)

    log = {
        'timestamp': datetime.utcnow().isoformat() + 'Z',
        'cwd': os.getcwd(),
        'args': args,
        'note': 'log generated by send_precommit_log'
    }

    out_file = os.path.join(out_dir, 'precommit_log.jsonl')
    with open(out_file, 'a', encoding='utf-8') as f:
        f.write(json.dumps(log, ensure_ascii=False) + '\n')


if __name__ == '__main__':
    main()
